[package]
name = "monte_carlo"
version = "0.1.0"
edition = "2021"

[lib]
name = "monte_carlo"
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.10.3"
hex = "0.4.3"
solana-program = "1.17.0"
thiserror = "1.0.49"
